# _config.yml
remote_theme: null

# Disable unwanted plugins if needed (e.g., jekyll-feed for a one-pager)
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
#   - jekyll-sass

whitelist:
  - jekyll-redirect-from

baseurl: "/vpipe"

sass:
  style: compressed


exclude:
  - README.md
  - assets/fonts/CabinetGrotesk_Complete/Fonts/WEB/README.md
  - Gemfile.lock
  - Gemfile

# Google Analytics
google_analytics: UA-126950686-1

matomo:
  url: matomo.sib.swiss
  siteId: "59"

# Add any other configurations or site-specific settings

collections:
  col_heroCarousel:
    output: false
    sort_by: "order"
  col_getStartedColumns:
    output: false
  col_whyVpipe:
    output: false
  footer:
    output: false
