# _config.yml
remote_theme: null

# Disable unwanted plugins if needed (e.g., jekyll-feed for a one-pager)
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
#   - jekyll-sass

whitelist:
  - jekyll-redirect-from

baseurl: "/vpipe"

sass:
  style: compressed


exclude:
  - README.md

# Add any other configurations or site-specific settings

collections:
  col_heroCarousel:
    output: true
    sort_by: "order"
  col_getStartedColumns:
    output: true
  col_whyVpipe:
    output: true
  footer:
    output: true