# _config.yml
remote_theme: null

# Disable unwanted plugins if needed (e.g., jekyll-feed for a one-pager)
# plugins:
#   - jekyll-sass

sass:
  style: compressed

# Add any other configurations or site-specific settings

collections:
  fp_heroCarousel:
    output: true
  fp_getStartedColumns:
    output: true
  fp_whyVpipe:
    output: true
  footer:
    output: true